# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cibibtsre < Formula
  desc "CIB IB Tech SRE CLI - High-performance AWS Control Tower BYOT onboarding automation"
  homepage "https://github.com/absa-group/cibibtsre-cli-go"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/absa-group/cibibtsre-cli-go/releases/download/v1.0.0/cibibtsre-1.0.0-Darwin-arm64.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"

      def install
        bin.install "cibibtsre"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/absa-group/cibibtsre-cli-go/releases/download/v1.0.0/cibibtsre-1.0.0-Darwin-x86_64.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"

      def install
        bin.install "cibibtsre"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/absa-group/cibibtsre-cli-go/releases/download/v1.0.0/cibibtsre-1.0.0-Linux-arm64.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"

      def install
        bin.install "cibibtsre"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/absa-group/cibibtsre-cli-go/releases/download/v1.0.0/cibibtsre-1.0.0-Linux-x86_64.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"

      def install
        bin.install "cibibtsre"
      end
    end
  end

  depends_on "git"

  test do
    system "#{bin}/cibibtsre", "--version"
  end
end
